spring:
  application:
    name: transaction-reconciliation-service
  profiles:
    active: h2

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8088

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
